CREATE TABLE applicant_desired_companies
(
    applicant_id      BIGINT NOT NULL,
    desired_companies VARCHAR(255)
);

CREATE TABLE applicants
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT                                  NOT NULL,
    skills  VARCHAR(255),
    cv_path VARCHAR(255),
    CONSTRAINT pk_applicants PRIMARY KEY (id)
);

CREATE TABLE referrals
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    applicant_id BIGINT                                  NOT NULL,
    referrer_id  BIGINT                                  NOT NULL,
    status       VARCHAR(255)                            NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    expires_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_referrals PRIMARY KEY (id)
);

CREATE TABLE referrers
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT                                  NOT NULL,
    company VARCHAR(255),
    CONSTRAINT pk_referrers PRIMARY KEY (id)
);

CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    telegram_id BIGINT                                  NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    email       VARCHAR(255),
    role        VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE applicants
    ADD CONSTRAINT uc_applicants_user UNIQUE (user_id);

ALTER TABLE referrers
    ADD CONSTRAINT uc_referrers_user UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_telegramid UNIQUE (telegram_id);

ALTER TABLE applicants
    ADD CONSTRAINT FK_APPLICANTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE referrals
    ADD CONSTRAINT FK_REFERRALS_ON_APPLICANT FOREIGN KEY (applicant_id) REFERENCES applicants (id);

ALTER TABLE referrals
    ADD CONSTRAINT FK_REFERRALS_ON_REFERRER FOREIGN KEY (referrer_id) REFERENCES referrers (id);

ALTER TABLE referrers
    ADD CONSTRAINT FK_REFERRERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE applicant_desired_companies
    ADD CONSTRAINT fk_applicant_desiredcompanies_on_applicant FOREIGN KEY (applicant_id) REFERENCES applicants (id);