-- ============================================
-- V1__initial_schema.sql
-- Initial Flyway migration for Referral Bot
-- ============================================

-- -------------------------
-- Users table
-- -------------------------
CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id BIGINT NOT NULL UNIQUE,
    name        VARCHAR(255) NOT NULL,
    email       VARCHAR(255) UNIQUE,
    role        VARCHAR(255) NOT NULL CHECK (role IN ('APPLICANT', 'REFERRER', 'NONE'))
);

-- -------------------------
-- Applicants table
-- -------------------------
CREATE TABLE applicants
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL UNIQUE,
    skills        VARCHAR(255),
    cv_path       VARCHAR(255),
    current_state VARCHAR(255) NOT NULL CHECK (
        current_state IN (
                          'NONE',
                          'REGISTERING_APPLICANT_NAME',
                          'REGISTERING_APPLICANT_SKILLS',
                          'REGISTERING_APPLICANT_CV',
                          'REGISTERING_APPLICANT_COMPANIES',
                          'APPLYING_FOR_REFERRAL',
                          'WAITING_FOR_REFERRAL'
            )
        )
);

-- -------------------------
-- Referrers table
-- -------------------------
CREATE TABLE referrers
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL UNIQUE,
    company       VARCHAR(255),
    current_state VARCHAR(255) NOT NULL CHECK (
        current_state IN (
                          'NONE',
                          'REGISTERING_REFERRER_NAME',
                          'REGISTERING_REFERRER_COMPANY',
                          'VIEWING_REFERRALS',
                          'SELECTING_REFERRAL',
                          'UPDATING_REFERRAL_STATUS'
            )
        ),
    referral_id   BIGINT
);

-- -------------------------
-- Referrals table
-- -------------------------
CREATE TABLE referrals
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    applicant_id BIGINT NOT NULL,
    referrer_id  BIGINT NOT NULL,
    status       VARCHAR(255) NOT NULL CHECK (status IN ('PENDING','APPROVED','REJECTED')),
    created_at   TIMESTAMP NOT NULL,
    expires_at   TIMESTAMP NOT NULL
);

-- -------------------------
-- Applicant desired companies (ElementCollection)
-- -------------------------
CREATE TABLE applicant_desired_companies
(
    applicant_id      BIGINT NOT NULL,
    desired_companies VARCHAR(255)
);

-- ==========================
-- Foreign keys
-- ==========================
ALTER TABLE applicants
    ADD CONSTRAINT fk_applicants_user FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE referrers
    ADD CONSTRAINT fk_referrers_user FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE referrers
    ADD CONSTRAINT fk_referrers_current_referral FOREIGN KEY (referral_id) REFERENCES referrals(id);

ALTER TABLE referrals
    ADD CONSTRAINT fk_referrals_applicant FOREIGN KEY (applicant_id) REFERENCES applicants(id);

ALTER TABLE referrals
    ADD CONSTRAINT fk_referrals_referrer FOREIGN KEY (referrer_id) REFERENCES referrers(id);

ALTER TABLE applicant_desired_companies
    ADD CONSTRAINT fk_applicant_desiredcompanies_applicant FOREIGN KEY (applicant_id) REFERENCES applicants(id);

