-- ============================================
-- V2__add_companies.sql
-- Introduce companies table and proper relations
-- ============================================

-- 1. Create companies table
CREATE TABLE companies
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

-- 2. Referrers: drop old string column, add FK to companies
ALTER TABLE referrers DROP COLUMN company;

ALTER TABLE referrers
    ADD company_id BIGINT;

ALTER TABLE referrers
    ADD CONSTRAINT fk_referrers_company FOREIGN KEY (company_id)
        REFERENCES companies(id);

-- 3. Applicants: drop old element collection table
DROP TABLE applicant_desired_companies;

-- 4. Create proper join table for applicants ↔ companies
CREATE TABLE applicant_desired_companies
(
    applicant_id BIGINT NOT NULL,
    company_id   BIGINT NOT NULL,
    PRIMARY KEY (applicant_id, company_id),
    CONSTRAINT fk_applicant_companies_applicant FOREIGN KEY (applicant_id)
        REFERENCES applicants(id) ON DELETE CASCADE,
    CONSTRAINT fk_applicant_companies_company FOREIGN KEY (company_id)
        REFERENCES companies(id) ON DELETE CASCADE
);
