server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  sql:
    init:
      platform: postgresql

bot:
  token: ${TELEGRAM_BOT_TOKEN}
